### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Siva952001** [PavanSaiSheshetti/Face_Recognition#1]
how to run streamlit python code,it shows error

**Comment by PavanSaiSheshetti** [comment]
Hello Siva, 
    Here is the command:
streamlit run Streamlit_Face_recg.py

Please go through the readme file for more information.

Thanks,
Pavan

**Comment by Siva952001** [comment]
C:\Users\DEV-037> streamlit run E:\employee face\Streamlit_Face_recg.py
Usage: streamlit run [OPTIONS] TARGET [ARGS]...
Try 'streamlit run --help' for help.

Error: Streamlit requires raw Python (.py) files, but the provided file has no extension.
For more information, please see https://docs.streamlit.io



this is the error which i got

**Comment by PavanSaiSheshetti** [comment]
Please go to that particular location where you have python file and execute the command there.
